import Head from "next/head"
import { Inter } from "next/font/google"
import ChatList from "@containers/ChatList"

const inter = Inter({ subsets: ["latin"] })

const chats = [
    {
        name: "Juan Trabajo",
        time: "12:30",
        message: "Mañana podemos hablarlo mejor y jajajajaasdadasdasdasdad",
        numMessages: 2,
        state: "online",
    },
    {
        name: "María",
        time: "10:14",
        message: "Vale!",
        numMessages: 1,
        state: "busy",
    },
    {
        name: "Pedro 1ºDAW",
        time: "Ayer",
        message: "Genial tío, pues ya hablamos en otro momento",
        state: "offline",
    },
    {
        name: "Paula prima",
        time: "Ayer",
        message: "√√ Graciaaas",
        state: "absent",
    },
    {
        name: "Darío",
        time: "Domingo",
        message: "√ ¿A qué hora?",
        state: "offline",
    },
]

/**
 * Esta es la página principal de la aplicación
 * @returns component
 */
const Home = () => {
    return (
        <>
            <Head>
                <title>ChatNow</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={inter.className}>
                <h1 className="text-2xl text-center mt-4">ChatNow</h1>
            </main>
            <ChatList chats={chats} />
        </>
    )
}

export default Home
